import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* NavBar  */}
        <div className="h-10 w-full flex justify-between items-center border-b-2 px-10 ">
          <div className=" cursor-pointer text-xl font-bold" >Medium</div>
          <div className="bg-blue-800 px-[10] cursor-pointer py-[5] rounded-2xl text-md font-bold text-white" >Profile</div>
        </div>
        {/* navBar ends */}
        {children}
      </body>
    </html>
  );
}
